# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank_proto/bank.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x61nk_proto/bank.proto\x12\nbank_proto\"F\n\x0e\x44\x65positMessage\x12\x12\n\naccount_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\"G\n\x0fWithdrawMessage\x12\x12\n\naccount_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\"0\n\x0fResponseMessage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\x97\x01\n\x0b\x42\x61nkService\x12\x42\n\x07\x44\x65posit\x12\x1a.bank_proto.DepositMessage\x1a\x1b.bank_proto.ResponseMessage\x12\x44\n\x08Withdraw\x12\x1b.bank_proto.WithdrawMessage\x1a\x1b.bank_proto.ResponseMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bank_proto.bank_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEPOSITMESSAGE._serialized_start=37
  _DEPOSITMESSAGE._serialized_end=107
  _WITHDRAWMESSAGE._serialized_start=109
  _WITHDRAWMESSAGE._serialized_end=180
  _RESPONSEMESSAGE._serialized_start=182
  _RESPONSEMESSAGE._serialized_end=230
  _BANKSERVICE._serialized_start=233
  _BANKSERVICE._serialized_end=384
# @@protoc_insertion_point(module_scope)
